on:  
  push: 
    branches: [develop]
permissions:
  contents: write
  
jobs:
  fix-paths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
          token: ${{ secrets.REPO_TOKEN }}
      - name: script
        shell: bash
        run: ./bin/replace_all.sh

      - name: Check the diff
        id: check_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Log next steps
        if: steps.check_diff.outputs.changed != 'true'
        run: |
          echo "Workflow detected that no changes are needed."

      - name: Conditional Commit
        if: steps.check_diff.outputs.changed == 'true'
        run: |
          echo "Preparing a commit."
          git config --local user.email "devconsole-team@pagoda.co"
          git config --local user.name "github-actions-bot"
          git commit -m "auto-update URL paths in response to marketing content update" -a
          git push