name: trigger nearorg_container workflow 
on: 
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: trigger nearorg_container workflow
        run: |
          curl -X POST  https://api.github.com/repos/near/nearorg_container/actions/workflows/78807110/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.REPO_TOKEN }} \
          --data '{"ref":"main"}'
      - uses: actions/checkout@v3
